person:
  name: zhangsan
  boss: true
  brith: 2019/19/9
  age: 18
  interest:
    - 篮球
    - 足球
    - voll
  animals: [阿猫,阿狗]
  score: [english: 80, math: 90]
  salarys:
    - 8000
    - 9000
  allPets:
    sick:
      - {name: 阿狗, weight: 99.89}
      - name: 阿猫
        weight: 21.89
      - name: 阿虫
        weight: 10.23
    health:
      - { name: 狗, weight: 18.89 }
      - name: 猫
        weight: 21.89
      - name: 虫
        weight: 45.2